apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../restic-secrets-manager
  - cloud-sync-rbac.yaml
  - cloud-sync-secret.yaml
  - cloud-sync-cronjob.yaml
images:
  - name: kubernetes-secrets-cloud-sync
    newTag: latest
    newName: devopsplaybookio/kubernetes-secrets-cloud-sync
