apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: restic-secrets-manager
resources:
  - base/namespace.yaml
  - base/pvc.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/secret.yaml
images:
  - name: restic-secrets-manager
    newTag: latest
    newName: devopsplaybookio/restic-secrets-manager
